version: '3'
services:
  api:
    build: ./api
    ports:
      - "3001:3001"
    environment:
      - HTTP_PORT=3001
  
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - HTTP_PORT=3000
  