version: '3'
services:
  api:
    image: rickvdl/todo-api:latest
    ports:
      - "3001:3001"
    environment:
      - HTTP_PORT=3001
  
  app:
    image: rickvdl/todo-app:dev
    ports:
      - "3000:3000"
    environment:
      - HTTP_PORT=3000
  